version: '3.9'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '10300:80'
  master:
    image: bitnami/spark:latest
    restart: always
    environment:
      - SPARK_MODE=master
    #  - SPARK_RPC_AUTHENTICATION_ENABLED=yes
    #  - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_SECRET}
      - SPARK_MASTER_OPTS=-Dspark.master.rest.enabled=true
      - SPARK_USER=spark
    #ports:
    #  - '7077:7077'
  worker:
    image: bitnami/spark:latest
    restart: always
    environment:
      - SPARK_MODE=worker
    #  - SPARK_RPC_AUTHENTICATION_ENABLED=yes
    #  - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_SECRET}
      - SPARK_MASTER_URL=${MASTER_URL:-spark://master:7077}
      - SPARK_WORKER_MEMORY=${WORKER_MEMORY:-8G}
      - SPARK_WORKER_CORES=${WORKER_CORES:-2}
      - SPARK_USER=spark
    ports:
      - '10301-10309:8081'