version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11235813
      POSTGRES_DB: FairGame
    ports:
      - "10001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 11235813
    ports:
      - "10002:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: always
  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass 11235813"
    environment:
      REDIS_HOST_PASSWORD: 11235813
    ports:
      - "10003:6379"
    volumes:
      - redis_data:/data
    restart: always
    
volumes:
  postgres_data:
  mongo_data:
  mongo_config:
  redis_data: