version: "3.9"
services:
  fairgame:
    image: fairgame:dev
    environment:
      SPRING_PROFILE: ${PROFILE}
      EXTERNAL_HOST_URL: http://fairgame:8080
      POSTGRES_URL: jdbc:postgresql://postgres:5432/FairGame
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_URL: mongodb://root:${MONGO_PASSWORD}@mongo:27017/FairGame?authMechanism=DEFAULT
      MONGO_HOST: mongo
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REMEMBER_ME_SECRET: ${REMEMBER_ME_SECRET}
      SPARK_MASTER_URL: https://nginx:80
    ports:
      - "10000:8080"
    depends_on:
      - postgres
      - redis
      - mongo
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11235813
      POSTGRES_DB: FairGame
    ports:
      - "10001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 11235813
    ports:
      - "10002:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: always
  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass 11235813"
    environment:
      REDIS_HOST_PASSWORD: 11235813
    ports:
      - "10003:6379"
    volumes:
      - redis_data:/data
    restart: always
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '10300:80'
  master:
    image: bitnami/spark:latest
    restart: always
    environment:
      - SPARK_MODE=master
    #  - SPARK_RPC_AUTHENTICATION_ENABLED=yes
    #  - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_SECRET}
      - SPARK_MASTER_OPTS=-Dspark.master.rest.enabled=true
      - SPARK_USER=spark
  worker:
    image: bitnami/spark:latest
    restart: always
    environment:
      - SPARK_MODE=worker
    #  - SPARK_RPC_AUTHENTICATION_ENABLED=yes
    #  - SPARK_RPC_AUTHENTICATION_SECRET=${SPARK_SECRET}
      - SPARK_MASTER_URL=${MASTER_URL:-spark://master:7077}
      - SPARK_WORKER_MEMORY=${WORKER_MEMORY:-8G}
      - SPARK_WORKER_CORES=${WORKER_CORES:-2}
      - SPARK_USER=spark


volumes:
  postgres_data:
  mongo_data:
  mongo_config:
  redis_data: