version: "2.1"
services:
  wikijs:
    image: requarks/wiki
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=FairWiki
      - DB_USER=postgres 
      - DB_PASS=${POSTGRES_PASSWORD}
    ports:
      - "10200:3000"
    volumes:
      - wiki_config:/config
      - wiki_data:/data
    
    
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: FairWiki
    ports:
      - "10201:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  wiki_data:
  wiki_config:

networks:
  default:
    driver: 'bridge'